##
## EPITECH PROJECT, 2019
## caesar
## File description:
## ex01
##

NAME	=	challenge02

all:	$(NAME)

$(NAME):
	@ln -fs ./fixed_xor.py ./$(NAME)

clean:
	@echo -e "clean fait"

fclean: clean
	@rm -f $(NAME)
	@echo -e "fclean fait"

re: fclean all

.PHONY: all fclean clean re challenge01
